name: mlagents
channels:
  - conda-forge
  - defaults
dependencies:
  - asttokens=2.4.1=pyhd8ed1ab_0
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2024.9.24=haa95532_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.2.2=pyhd8ed1ab_0
  - debugpy=1.8.7=py310h9e98ed7_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_0
  - executing=2.1.0=pyhd8ed1ab_0
  - importlib-metadata=8.5.0=pyha770c72_0
  - ipykernel=6.29.5=pyh4bbf305_0
  - ipython=8.29.0=pyh7428d3b_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jupyter_client=8.6.3=pyhd8ed1ab_0
  - jupyter_core=5.7.2=py310h5588dad_0
  - krb5=1.21.3=hdf4eb48_0
  - libffi=3.4.4=hd77b12b_1
  - libsodium=1.0.20=hc70643c_0
  - m2-base=1.0.0=3
  - m2-bash=4.3.042=5
  - m2-bash-completion=2.3=2
  - m2-catgets=1.1=3
  - m2-coreutils=8.25=102
  - m2-dash=0.5.8=2
  - m2-file=5.25=2
  - m2-filesystem=2016.04=4
  - m2-findutils=4.6.0=2
  - m2-gawk=4.1.3=2
  - m2-gcc-libs=5.3.0=4
  - m2-gettext=0.19.7=4
  - m2-gmp=6.1.0=3
  - m2-grep=2.22=4
  - m2-gzip=1.7=2
  - m2-inetutils=1.9.2=2
  - m2-info=6.0=2
  - m2-less=481=2
  - m2-libasprintf=0.19.7=4
  - m2-libcatgets=1.1=3
  - m2-libcrypt=1.3=2
  - m2-libgettextpo=0.19.7=4
  - m2-libiconv=1.14=3
  - m2-libintl=0.19.7=4
  - m2-liblzma=5.2.2=2
  - m2-libpcre=8.38=2
  - m2-libreadline=6.3.008=8
  - m2-libutil-linux=2.26.2=2
  - m2-libxml2=2.9.2=3
  - m2-mintty=1!2.2.3=2
  - m2-mpfr=3.1.4=2
  - m2-msys2-launcher-git=0.3.28.860c495=2
  - m2-msys2-runtime=2.5.0.17080.65c939c=3
  - m2-ncurses=6.0.20160220=2
  - m2-sed=4.2.2=3
  - m2-tftp-hpa=5.2=2
  - m2-time=1.7=2
  - m2-ttyrec=1.0.8=2
  - m2-tzcode=2015.e=2
  - m2-util-linux=2.26.2=2
  - m2-which=2.21=3
  - m2-zlib=1.2.8=4
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - msys2-conda-epoch=20160418=1
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - openssl=3.3.2=h2466b09_0
  - packaging=24.1=pyhd8ed1ab_0
  - parso=0.8.4=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pip=24.2=py310haa95532_0
  - platformdirs=4.3.6=pyhd8ed1ab_0
  - prompt-toolkit=3.0.48=pyha770c72_0
  - psutil=6.1.0=py310ha8f682b_0
  - pure_eval=0.2.3=pyhd8ed1ab_0
  - pygments=2.18.0=pyhd8ed1ab_0
  - python=3.10.12=he1021f5_0
  - python_abi=3.10=2_cp310
  - pyzmq=26.2.0=py310h656833d_3
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.45.3=h2bbff1b_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tk=8.6.14=h0416ee5_0
  - tornado=6.4.1=py310ha8f682b_1
  - traitlets=5.14.3=pyhd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_0
  - tzdata=2024a=h04d1e81_0
  - ucrt=10.0.22621.0=h57928b3_1
  - vc=14.40=h2eaa2aa_1
  - vc14_runtime=14.40.33810=hcc2c482_22
  - vs2015_runtime=14.40.33810=h3bf8584_22
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - wheel=0.44.0=py310haa95532_0
  - xz=5.4.6=h8cc25b3_1
  - zeromq=4.3.5=ha9f60a1_6
  - zipp=3.20.2=pyhd8ed1ab_0
  - zlib=1.2.13=h8cc25b3_1
  - pip:
      - absl-py==2.1.0
      - ale-py==0.10.1
      - attrs==24.2.0
      - box2d-py==2.3.5
      - cattrs==1.5.0
      - certifi==2024.8.30
      - cffi==1.17.1
      - charset-normalizer==3.3.2
      - chex==0.1.87
      - cloudpickle==3.0.0
      - contourpy==1.3.0
      - cycler==0.12.1
      - cython==0.29.37
      - decorator==4.4.2
      - etils==1.10.0
      - farama-notifications==0.0.4
      - fasteners==0.19
      - filelock==3.13.1
      - flax==0.10.0
      - fonttools==4.54.1
      - fsspec==2024.2.0
      - glfw==2.7.0
      - grpcio==1.48.2
      - gym==0.26.2
      - gym-notices==0.0.8
      - gymnasium==1.0.0
      - h5py==3.12.1
      - huggingface-hub==0.25.1
      - humanize==4.11.0
      - idna==3.10
      - imageio==2.36.0
      - imageio-ffmpeg==0.5.1
      - importlib-resources==6.4.5
      - jax==0.4.34
      - jaxlib==0.4.34
      - jinja2==3.1.3
      - kiwisolver==1.4.7
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.9.2
      - mdurl==0.1.2
      - ml-dtypes==0.5.0
      - moviepy==1.0.3
      - mpmath==1.3.0
      - msgpack==1.1.0
      - mujoco==3.2.4
      - mujoco-py==2.1.2.14
      - networkx==3.2.1
      - numpy==1.24.1
      - onnx==1.15.0
      - opencv-python==4.10.0.84
      - opt-einsum==3.4.0
      - optax==0.2.3
      - orbax-checkpoint==0.7.0
      - pettingzoo==1.15.0
      - pillow==10.4.0
      - proglog==0.1.10
      - protobuf==3.20.3
      - pycparser==2.22
      - pygame==2.6.1
      - pyopengl==3.1.7
      - pyparsing==3.2.0
      - pypiwin32==223
      - python-dateutil==2.9.0.post0
      - pywin32==306
      - pyyaml==6.0.2
      - requests==2.32.3
      - rich==13.9.2
      - scipy==1.14.1
      - setuptools==75.2.0
      - swig==4.2.1
      - sympy==1.12
      - tensorboard==2.18.0
      - tensorboard-data-server==0.7.2
      - tensorstore==0.1.66
      - toolz==1.0.0
      - torch==2.2.2+cu121
      - tqdm==4.66.5
      - typing-extensions==4.9.0
      - urllib3==2.2.3
      - werkzeug==3.0.4
prefix: C:\Users\rullo\anaconda3\envs\mlagents
